### ISSUE TITLE
GitOps Support Docs

### ISSUE THREAD

**Issue by DreamingRaven** [goauthentik/helm#127]
Hey Authentik team.

I just wanted to say thank you for all your hard work, I am loving Authentik, and I am keen to see it grow!

I wanted to open this issue as the docs are a little light in areas that concern GitOps. At this current time I have created [my own Helm chart](https://gitlab.com/GeorgeRaven/authentik-helm) to add some much needed functionality to cover some of the GitOps use cases like utilization of k8s secrets.

Is there anywhere in the documentation that has a bit more elaborate description of blueprints as I cannot seem to get a good handle on the blueprint specification, the available fields, and what they actually do.

So for instance in the docs there is a relatively [short example of the file structure](https://goauthentik.io/developer-docs/blueprints/v1/structure) however there is a much [more complex example](https://goauthentik.io/developer-docs/blueprints/v1/example)  which has little documentation but seems to make much more thorough use of the also partially explained [yaml tags](https://goauthentik.io/developer-docs/blueprints/v1/tags). However this for me is not enough to reasonably make blueprints as needed.

I believe blueprints are the key to Authentik and GitOps for persistent and consistent spin up and spin down of clusters in testing and production. If possible I would also like to create a GitOps documentation page for Kubernetes specifically as it is preferable in k8s (in my opinion) to spin up with all the desired flows configuration theming etc out of the gate without any clicks. Environment variables (they work well)  and sealed-secrets (of my own addition) seem to cover half this GitOps use case and I believe blueprints is the final hurdle for me.

**Comment by BeryJu** [comment]
an example for an LDAP Provider, app and outpost:

```yaml
entries:
- model: authentik_blueprints.metaapplyblueprint
  attrs:
    identifiers:
      name: Default - Authentication flow
    required: true
- attrs:
    authorization_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
    base_dn: DC=ldap,DC=goauthentik,DC=io
    bind_mode: cached
    gid_start_number: 4000
    search_group: !Find [authentik_core.group, [name, "authentik Admins"]]
    search_mode: cached
    uid_start_number: 2000
  id: provider
  identifiers:
    name: test
  model: authentik_providers_ldap.ldapprovider
- attrs:
    name: ldap
    policy_engine_mode: any
    provider: !KeyOf provider
  id: app
  identifiers:
    slug: ldap
  model: authentik_core.application
- attrs:
    config:
      authentik_host: http://localhost:9000/
    providers:
    - !KeyOf provider
    type: ldap
  id: outpost
  identifiers:
    name: ldap
  model: authentik_outposts.outpost
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2022-08-31 21:14:20.484928+00:00
version: 1
```

There aren't examples for every object, but in general the JSON schema should help (https://goauthentik.io/blueprints/schema.json)

the fields under `attrs` and `identifiers` are all fields that are available via API, as that's what the blueprints use internally.

you can also use `ak export_blueprint` in the server/worker container to export the current config to a blueprint

**Comment by DreamingRaven** [comment]
Actually that is quite helpful thanks for that. Also thanks for getting back to me so quickly.

It took me a second to break it down from the schema, but after I converted it into more comfortable (for me atleast) YAML, I could see a good number of the `properties` that I had been looking for for a good number of maps.

One liner for anyone else who likes YAML:
```bash
curl https://goauthentik.io/blueprints/schema.json | yq --yaml-output
```

I also see what you mean by there are examples for every object. At first I thought you meant blueprint entry examples but you actually mean properties of the schema aren't fully populated in the schema.json (correct me if I am wrong). E.G shema.json does not list sub-properties of `attrs` map, which you have used in the example LDAP app, provider, and outpost metaapplyblueprint blueprint.

Is there a way I can go any deeper and find even more of these properties somewhere? Maybe in the specific models? As I want to get a more complete picture so that I can generate these blueprints without the use of the GUI since really I want to generate this decoratively in helm / operator (I am building an authentik operator). I can always reverse engineer from clicked together bits and export_blueprint as you mentioned. 
Ideally it would be a lot more consistent to have an API I can gather extract this information from if there is such a thing atm, this would also help me in the long run maintain compatibility.

So like ``kubectl api-resources``, ``kubectl get crd`` or ``kubectl explain`` (or query the specific resources) but for authentik blueprint properties.

**Comment by BeryJu** [comment]
You can use these settings in vscode to load the schema for yaml files:

```json
    "yaml.schemas": {
        "https://goauthentik.io/blueprints/schema.json": "blueprints/**/*.yaml"
    },
```

Yes, the schema doesn't list all properties of all possible objects, as much as I want to do that it's not that easy. All the field names in `attrs` and `identifiers` are the same as for the API, you can use https://goauthentik.io/developer-docs/api/browser as a reference

I'm actually also thinking about building a (very simple) kubernetes operator into authentik, with a single Blueprint CRD that is automatically recreated/reconcilled in authentik

**Comment by DreamingRaven** [comment]
Yeah funnily enough that is exactly what I am doing among other CRDs.

I am currently making AkBlueprint, AkOutpost, AkProvider, and AkApplication CRDs and the managing operator. I feel it would be extremely convenient to be able to configure authentik in a kube native manner and have it dynamically load configuration in this way which is why I started adding it. In particular my end goal is that you can configure an application in a given namespace and have the controller automatically configure its ingress resource with forward auth and or any providers it needs for integration.

Thanks for the help, I appreciate it. I think I have most of what I need now anyway. If I have any specific issues with blueprints I may drop them in here if that is amiable.

**Comment by genofire** [comment]
Here are a list of Operator that i find.
https://github.com/goauthentik/authentik/issues/4558

But yes a official Operator with an stabil API whould be nice.
But that need person to maintain, so even https://gitlab.com/GeorgeRaven/authentik-manager switch to blueprint.

so i believe as an first step https://github.com/goauthentik/helm/pull/146 with declararive blueprints (https://github.com/goauthentik/authentik/issues/5300) could be fast implemented and would solve the most problems

**Comment by DreamingRaven** [comment]
I have been working on this the last few days, the blueprint functionality should be in place very soon!
I am chose to go with [internal](https://goauthentik.io/developer-docs/blueprints/#storage---internal) storage, as it simplifies everything substantially since it wont fight against any gitops orchestration mechanism.

Currently:
- blueprint CRD is found or changed:
  - attempt to get the CRD
    - if the blueprint has been removed it will remove it from the DB by path (TODO)
  - load the CRD into my api definition / stucts to confirm it conforms to what is expected to be there
  - create a configmap of this CRD or update the existing one (this is so I could mount it in the old version of the operator)
  - create a connection to postgresql
  - query the db in the ``authentik_blueprints_blueprintinstance`` table to check if the blueprint is there already
    -  if its there is an entry with the given path it will check if it matches and update if not (TODO)
    - if it is not there it will add a new row to the table with the blueprint in the content field with the given path (TODO)

I will drop a message here when its done. Once the last 3 tasks are complete it should be fully functional, after that it will be just keeping everything compatible in case the db structure changes / migrates, and adding new higher level CRDs to automate larger tasks. The ak CRD is already complete and manages the stack of authentik already although I want to add more automation to this going forward like rolling updates etc.

But yeah I get you, an official operator would have been nicer but its a lot to ask, they are such complex beasts and adds a lot more headaches for the authentik guys.

**Comment by DreamingRaven** [comment]
Ok I have the base blueprint handling just about sorted which I will release soon. This is a blueprint that was loaded from a cluster CRD using the operator:
![blueprint-sample](https://github.com/goauthentik/helm/assets/10534713/e9a9e5f4-4715-472d-a6da-f8492449301e)
However one important case that I need to find a good solution for is default blueprint overrides. So say someone wanted to deploy a blueprint that overrides the default behavior for say the login page using:
```
apiVersion: akm.goauthentik.io/v1alpha1
kind: AkBlueprint
metadata:
  labels:
    app.kubernetes.io/name: akblueprint
    app.kubernetes.io/instance: akblueprint-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: akblueprint-sample
spec:
  file: /blueprints/default/10-flow-default-authentication-flow.yaml
  blueprint:
    version: 1
    metadata:
      name: Default - Authentication flow
    entries:
    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Default - Password change flow
        required: false
    - attrs:
        designation: authentication
        # TODO: (USER) adjust the name, title to match your branding
        name: login
        title: Welcome to akm!
        authentication: require_unauthenticated
      identifiers:
        slug: default-authentication-flow
      model: authentik_flows.flow
      id: flow
    - attrs:
        backends:
        - authentik.core.auth.InbuiltBackend
        - authentik.sources.ldap.auth.LDAPBackend
        - authentik.core.auth.TokenBackend
        configure_flow: !Find [authentik_flows.flow, [slug, default-password-change]]
      identifiers:
        name: default-authentication-password
      id: default-authentication-password
      model: authentik_stages_password.passwordstage
    - identifiers:
        name: default-authentication-mfa-validation
      id: default-authentication-mfa-validation
      model: authentik_stages_authenticator_validate.authenticatorvalidatestage
    - attrs:
        user_fields:
        - email
        - username
      identifiers:
        name: default-authentication-identification
      id: default-authentication-identification
      model: authentik_stages_identification.identificationstage
    - identifiers:
        name: default-authentication-login
      id: default-authentication-login
      model: authentik_stages_user_login.userloginstage
    - identifiers:
        order: 10
        stage: !KeyOf default-authentication-identification
        target: !KeyOf flow
      model: authentik_flows.flowstagebinding
    - identifiers:
        order: 20
        stage: !KeyOf default-authentication-password
        target: !KeyOf flow
      model: authentik_flows.flowstagebinding
    - identifiers:
        order: 30
        stage: !KeyOf default-authentication-mfa-validation
        target: !KeyOf flow
      model: authentik_flows.flowstagebinding
    - identifiers:
        order: 100
        stage: !KeyOf default-authentication-login
        target: !KeyOf flow
      model: authentik_flows.flowstagebinding
```
So that it now says something different (in this case welcome to AKM). Usually you would overwrite the actual file itself with your new version but when you are interacting with the internal storage mechanism or just targeting the db directly I do not see a clear way to do so. If I were to overwrite the db entry that comes from a default file I expect that the file would then overwrite my table changes again whenever authentik re-scans the files and compares their contents. The clearest solution I can think of is to actually remove all the default blueprints and instead package them as default CRDs deployed with authentik. However I would like to avoid this as I am not certain what behavior authentik will have in the few moments it has no blueprints and I do not want to suffer any drift if the default blueprints get updated or changed over time compared to my CRDs.
