### ISSUE TITLE
OCI registry-backed blueprints

### ISSUE THREAD

**Issue by cskwrd** [goauthentik/helm#147]
It appears that the helm chart has support for defining blueprints via a configmap. Is there a way to configure authentik to apply OCI registry-backed blueprints via the chart?

**Comment by BeryJu** [comment]
There's no direct way to specify a list of OCI uris to use as blueprint instances, but as you can manage any model via blueprint instance, you can use a blueprint that creates more blueprints:

```yaml
version: 1
metadata:
  name: OCI blueprints
entries:
  - model: authentik_blueprints.blueprintinstance
    identifiers:
      name: my-blueprint-name
    attrs:
      context:
        foo: bar
      path: oci://ghcr.io/<username>/<package-name>:<ref>
  - model: authentik_blueprints.blueprintinstance
    identifiers:
      name: my-other-blueprint-name
    attrs:
      context:
        foo: bar
      path: oci://ghcr.io/<username>/<package-name>:<ref>
```

(the `context` key is optional, just make sure the `name` of each of the blueprints is different)
