### ISSUE TITLE
Problem Pod authentik-server 

### ISSUE THREAD

**Issue by Luskan777** [goauthentik/helm#17]
Hi Guys, 

I have a problem in pod authentik-server, the pod return this log

![Deepin Screenshot_selecionar área_20210803120234](https://user-images.githubusercontent.com/71342479/128038883-83c43f0d-2c06-4c4f-a7a7-ccc8430483ce.png)

PS: only this pod is not running

**Comment by Luskan777** [comment]
To be more exact, it returns these two problems:
![Deepin Screenshot_selecionar área_20210803120844](https://user-images.githubusercontent.com/71342479/128039748-78a19734-3eda-4367-9d35-bd296fda40f9.png)

**Comment by ApolloDS** [comment]
I have the problem that redis is not started within the helm chart.
error message in log: {"event": "Redis Connection failed, retrying... (Error 111 connecting <host>...

**Comment by ApolloDS** [comment]
> I have the problem that redis is not started within the helm chart.
> error message in log: {"event": "Redis Connection failed, retrying... (Error 111 connecting ...

I have it running now. I had to create a redis install with my terraform config.
It seems that helm is not creating the pod with redis as specified in dependencies.

**Comment by ApolloDS** [comment]
> To be more exact, it returns these two problems:
> ![Deepin Screenshot_selecionar área_20210803120844](https://user-images.githubusercontent.com/71342479/128039748-78a19734-3eda-4367-9d35-bd296fda40f9.png)

Check the log of the pod/container, you should see what the problem is.

**Comment by BeryJu** [comment]
what does your values.yaml file look like? There is a bundled redis, but it has to be enabled:

```yaml

authentik:
  log_level: debug
  secret_key: 5up3r53cr37K3y
  postgresql:
    password: au7h3n71k
  redis:
    password: au7h3n71k

postgresql:
  enabled: true
  postgresqlPassword: au7h3n71k
  persistence:
    enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: au7h3n71k
```
