### ISSUE TITLE
Regression: Service Account Name

### ISSUE THREAD

**Issue by ChandonPierre** [goauthentik/helm#176]
Somewhere between #150 and #163 a regression was introduced where the `serviceAccount` name created by the `authentik-remote-cluster` chart does not match the service account being mounted into the worker container.:

```
# Source: authentik/charts/serviceAccount/templates/service-account.yaml
kind: ServiceAccount
metadata:
  name: release-name
```

```
# Source: authentik/templates/worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-authentik-worker
.......
    spec:
      serviceAccountName: release-name-authentik
```

One of the naming schemes of [`authentik.names.fullname`](https://github.com/goauthentik/helm/blob/2c53130e87dc5baa12a66092ea475c384a2fdc06/charts/authentik/templates/_helpers.tpl#L60) OR [`authentik-remote-cluster.fullname`](https://github.com/goauthentik/helm/blob/2c53130e87dc5baa12a66092ea475c384a2fdc06/charts/authentik-remote-cluster/templates/_helpers.tpl#L13) should change to fix this
