### ISSUE TITLE
Option to disable default Blueprints

### ISSUE THREAD

**Issue by mittler-works** [goauthentik/helm#179]
When deploying authentik via Helm, there is an option to specify a list of blueprints with ConfigMaps that are mounted into the Worker.

The specified blueprints are mounted at `/blueprints/mounted/{{ $name }}` as you can see [here](https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/worker-deployment.yaml#L102).

So there is no way to overwrite the default blueprints in `/blueprints/default`, `/blueprints/example` and `/blueprints/system` here.

The developer documentation says [here](https://goauthentik.io/developer-docs/blueprints/#storage---file) that you can disable the default blueprints by mounting other (e.g. empty) files or directories in the corresponding paths.

This is not possible with this chart. I don't want many of the default objects (e.g. the default flows) in my deployment, because I configure my objects myself (and differently). Here, after deployment, the default objects have to be deleted manually and that is inconvenient.

It would be nice if there was a way to disable default Blueprints in this Chart.

**Comment by rissson** [comment]
You can add extra volumes to disable those:
```yaml
volumesMounts:
  - name: blueprints-default-override
    mountPath: /blueprints/default
volumes:
  - name: blueprints-default-override
    emptyDir: {}
```
