### ISSUE TITLE
Passing additional values to inner Postgres helmchart?

### ISSUE THREAD

**Issue by p4block** [goauthentik/helm#216]
I would like to configure the Postgres with a pre-existing claim 

```
  postgresql:
    enabled: true
    postgresqlPassword: "7ucC2kxRgHbr9oh7KdYyxb3I"
    primary:
      persistence:
        existingClaim: authentik-pvc
```

Intutively this should work (passing values to the dependent chart) but it doesn't seem to do anything.

(this inevitably raises the question of why vendorize the chart instead of just adding upstream bitnami with a few more lines of example values.yaml?)

**Comment by rissson** [comment]
We'll try to go back to a non-vendorized version of the chart with 2024.1

**Comment by p4block** [comment]
Nice to hear! In the meantime I simply disabled the builtin chart and added the upstream chart. The name of the deployed service even matches so there's no configuration needed.
Because of how I deploy apps this is pretty straightforward ("dummy" helmcharts that depend on 1 or more helmcharts, and with the ability to inject some yaml) 

Here for reference if anyone wants to do it like I did.

Chart.yaml```
apiVersion: v2
name: authentik
version: 1.0.0
dependencies:
- name: authentik
  version: 2023.10.3
  repository: https://charts.goauthentik.io
- name: postgresql # de-vendorize postgres
  version: 13.2.14
  repository: https://charts.bitnami.com/bitnami
```

Values.yaml```
authentik:

  postgresql:
    enabled: false

  redis:
    enabled: true
    architecture: standalone

  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
    # Specify external host name
    - host: authentik.bla.bla
      paths:
      - path: "/"
        pathType: Prefix


postgresql:
  global:
    postgresql:
      auth:
        username: authentik
        database: authentik

  primary:
    persistence:
      existingClaim: "authentik-postgres-16-pvc"
```

And a pvc+pv yaml in the templates folder.
