### ISSUE TITLE
Feature Request: Add support to import blueprints from Secrets

### ISSUE THREAD

**Issue by janosmiko** [goauthentik/helm#221]
Use-case: we are storing our secrets in external Vaults and use external-secrets operator to sync the external secrets with Kubernetes.

As we store various secrets in the authentik-blueprints (eg: certs, keys), in my opinion it would make sense to make it possible to import blueprints from k8s secrets as well, not just from configmaps.

**Comment by BeryJu** [comment]
the `blueprints` option doesn't really do anything special, it simply mounts the config map under `/blueprint/mounted/{{ configmap-name }}`, so you can `.volumeMounts` and `.volumes` to do the same with secrets

@rissson do we also want to make a breaking change for this for 2024.1 to allow secrets to be mounted?

**Comment by rissson** [comment]
Sure, we can

**Comment by janosmiko** [comment]
Thanks for the info @BeryJu ,

If anyone needs a working solution

Content of the Azure Key Vault secret is formatted as JSON:
```json
{
  "authentik-blueprint.yaml": "BASE64-ENCODED-BLUEPRINT"
}
```

The external-secret (it extracts the KV secret content to kubernetes):
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-blueprint
  namespace: authentik
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: Base64
        key: authentik-blueprint
        property: authentik-blueprint.yaml
      secretKey: authentik-blueprint.yaml
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv
```

And finally, I had to update the Authentik helm chart with the following volumes / volumeMounts:
```yaml
volumes:
  - name: authentik-blueprint
    secret:
      secretName: authentik-blueprint
      items:
        - key: authentik-blueprint.yaml
          path: authentik-blueprint.yaml
volumeMounts:
  - name: authentik-blueprint
    mountPath: /blueprints/mounted
    readOnly: true
```
