### ISSUE TITLE
Redis: Cannot define StorageClass

### ISSUE THREAD

**Issue by NigelVanHattum** [goauthentik/helm#222]
**k8s version:** v1.28.0
**helm version:** v3.12.3
**Chart version:** 2023.10.4

**Problem**
While trying to deploy the Authentik chart it is not able to create a PVC, since I cannot define a StorageClass. My cluster has no default StorageClass, to reduce incidental persistent files. 

My helm values (note all sensitive values are located elsewhere): 
```yaml
authentik:
    error_reporting:
        enabled: true
    postgresql:
        host: <<DB_HOST>>

service:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: internet

geoip:
  enabled: true
  editionIds: "GeoLite2-City"
  image: maxmindinc/geoipupdate:v4.8
  updateInterval: 8

autoscaling:
  server:
    enabled: true

redis:
  enabled: true
  global.storageClass: "nfs-csi-redis"
```

Moving " global.storageClass: "nfs-csi-redis" " to the root, does not help. 

I would have expected that the "global.storageClass" was picked up by the Bitnami chart, but it does not seem so. The PVC fails to create with the following message:

> FailedBinding
no persistent volumes available for this claim and no storage class is set

**Comment by robodrome** [comment]
That didn't work for me. When doing:

```bash
--set redis.enabled=true \
--set redis.global.storageClass=authentik-sc
```

I get this as a persistent volume:

```yaml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
status:
  phase: Pending
```

Is there someone who know how to set the `redis` subchart to use a storage class for persistent storage?
