### ISSUE TITLE
support referencing kubernetes secrets for postgres & redis configuration

### ISSUE THREAD

**Issue by kaplan-michael** [goauthentik/helm#227]
Hey,

Would it be possible to support secret and key referencing when setting the postgres user, password and host? 
In my case, we use postgres operator and that already prepares a secret(autogenerated) with these values. 

something like this 

  postgresql:
    passwordSecret:
      key: password
      name: somepg-cluster
    usernameSecret:
      key: username
      name: somepg-cluster

and so on. 

Perhaps this would be useful for redis as well.(as that is also commonly deployed with operators. 
I think it would simplify the declarative deployment, as you can specify you want a db(something else will prepare it) and you can then just reference those details, instead of having to do some hacky lookups.

**Comment by rissson** [comment]
Hi, you can already do so with:

```yaml
authentik:
  postgresql:
    host: my-postgres
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
volumeMounts:
  - name: postgres-creds
    mountPath: /postgres-creds
volumes:
  - name: postgres-creds
    secret:
      secretName: authentik-postgres-credentials
```
Also, this supports hot-reload of postgres credentials with some of the latest versions of authentik (I can't remember when we started supporting this)
