### ISSUE TITLE
PDB does not use right set of labels as selector

### ISSUE THREAD

**Issue by arthur-leclerc** [goauthentik/helm#232]
Hi,

The PDB deployed by the Helm Chart does not use the right set of labels as selector, currently the PDB uses `authentik.labels` when I think it should use `authentik.labels.selectorLabels`, the consequence is that the PDB watch on too many labels and can't find any pods.

[server-pdb.yaml](https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/server-pdb.yaml#L20-L23)

```yaml
  selector:
    matchLabels:
      {{- include "authentik.labels" $ | nindent 6 }}
      app.kubernetes.io/component: server
```

[server-deployment.yaml](https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/server-deployment.yaml#L23-L28)

```yaml
  template:
    metadata:
      labels:
        {{- include "authentik.labels.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: "server"
        app.kubernetes.io/version: "{{ trunc 63 $.Values.image.tag }}"
```

Edit: I just saw #230, I'm leaving this issue open to provide information that the PDBs are not currently working, the Chart rework will fixes this problem.
