### ISSUE TITLE
additionalObjects "cannot retrieve Template.Basepath from values inside tpl function"

### ISSUE THREAD

**Issue by gmatiukhin** [goauthentik/helm#241]
Hello! I'm setting up Authentik using this helm chart.

I decided to add a pvc description using `additionalObjects` list.
This is how it looks like:
```yaml
additionalObjects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: authentik-media-pvc
      namespace: authentik
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: authentik-storage-class
      resources:
        requests:
          storage: 1Gi
```

However when I try to install it I get the following error:
```
Error: INSTALLATION FAILED: template: authentik/templates/additional-objects.yaml:3:4: executing "authentik/templates/additional-objects.yaml" at <tpl (toYaml .) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media-pvc
  namespace: authentik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: authentik-storage-class: "BasePath" is not a value
```

This issue helm/helm#5979 seems to be relevant.
