### ISSUE TITLE
Error when enabling geoip in chart

### ISSUE THREAD

**Issue by arshesney** [goauthentik/helm#244]
Tested with chart versions 2024.2.0 and 2024.2.1
Helm: ```version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.20.11"}```

Enabling geoip sidecars returns the following error:
```
Error: INSTALLATION FAILED: YAML parse error on authentik/templates/server/deployment.yaml: error converting YAML to JSON: yaml: line 106: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 106: mapping values are not allowed in this context
```

```yaml
# values.yaml
global:
  image:
    tag: "2024.2.1"

  tolerations:
  - effect: NoSchedule
    key: project
    operator: Exists

  volumeMounts:
  - name: storage
    mountPath: /media
    subPath: media
  - name: storage
    mountPath: /templates
    subPath: templates
  - name: ldap-cert
    mountPath: /certs/ldap

  volumes:
  - name: storage
    nfs:
      server: <snip>
      path: /nfs/authentik
  - name: ldap-cert
    secret:
      secretName: ldap
      items:
      - key: tls.crt
        path: ldap.crt
      - key: tls.key
        path: ldap.key

authentik:
  secret_key: "<snip>"
  email:
    host: "<snip>"
    port: 25
    from: "<snip>"
  error_reporting:
    enabled: true
    environment: "k3s"
  postgresql:
    host: "postgres.postgres.svc"
    name: "authentik"
    user: "authentik"
    password: "<snip>"
  redis:
    host: "redis-server.redis.svc"
    password: "<snip>"

server:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - <snip>
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 25
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: type
              operator: In
              values:
              - cpu-hungry
          topologyKey: "kubernetes.io/hostname"

  livenessProbe:
    initialDelaySeconds: 60

  readinessProbe:
    initialDelaySeconds: 60

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
    - <snip>
    tls:
    - secretName: <snip>
      hosts:
      - <snip>

geoip:
  enabled: true
  existingSecret:
    secretName: geoip-secret

```
