### ISSUE TITLE
nodeSelectorTerms is set to an empty object when configuring server or worker affinity

### ISSUE THREAD

**Issue by gmatiukhin** [goauthentik/helm#251]
I'm using this chart to set up authentik. I want the server pods to be deployed only to a specific set of zones, but the worker pods should not be restricted.

In order to achieve that I have omitted the `global.affinity` part from my values and configured the `server.affinity` like this:
```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpression:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - zone1
          - zone2
```

When deploying the chart server pods fail to schedule with the following error:
```
0/8 nodes are available: 8 node(s) didn't match Pod's node affinity/selector. preemption: 0/8 nodes are available: 8 Preemption is not helpful for scheduling..
```
When looking at the server pod config with `kubectl -n authentik get pod -l app.kubernetes.io/component=server -o yaml` I see that the affinity was set incorrectly:
```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - {}
```

Further testing revealed that the same thing happens when configuring `worker.nodeAffinity`.
`podAffinity` and `podAntiAffinity` were not tested but might be also affected.
