### ISSUE TITLE
Authentik shows internal pod IPv6 for Users instead of public IP

### ISSUE THREAD

**Issue by MTRNord** [goauthentik/helm#254]
I might be missing something obvious but with kubernetes and the traefik ingress it seems like I am seeing only internal IPs on users like `fd00::6`. Is there a way to make sure it sees the outside IP instead?

**Comment by rissson** [comment]
You may be looking for `AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS` (https://docs.goauthentik.io/docs/installation/configuration#listen-settings)
In the helm chart, it looks like:
```yaml
authentik:
  listen:
    trusted_proxy_cidrs: "fd00::/7"
````
