### ISSUE TITLE
Install server instance as a DaemonSet

### ISSUE THREAD

**Issue by eternity1984** [goauthentik/helm#265]
I wanted to install an authentik server instance as a DaemonSet. 

I have updated the Helm chart: [commit](https://github.com/eternity1984/helm-authentik/commit/0087e0ba9ed36660a93df633a1088173ac6739ce)
May I submit a pull request?

The added parameter is as follows:
```yaml
## authentik server
server:
  # -- Deployment or DaemonSet
  kind: Deployment

  ...
```

The result when `server.kind=DaemonSet` is set:
```
NAME                                READY   STATUS    RESTARTS   AGE     IP               NODE
authentik-postgresql-0              1/1     Running   0          2m12s   172.25.206.214   k8s-worker-d967f7c1
authentik-redis-master-0            1/1     Running   0          2m12s   172.25.74.155    k8s-worker-a21b5f5c
authentik-server-bfr4t              1/1     Running   0          2m12s   172.25.182.100   k8s-master-2
authentik-server-bxzrl              1/1     Running   0          2m12s   172.25.168.18    k8s-master-3
authentik-server-z9qj7              1/1     Running   0          2m12s   172.25.196.33    k8s-master-1
authentik-worker-6b8bfb9b46-2bdpb   1/1     Running   0          2m12s   172.25.206.212   k8s-worker-77d96fc1
authentik-worker-6b8bfb9b46-j5gml   1/1     Running   0          2m12s   172.25.74.150    k8s-worker-a21b5f5c
authentik-worker-6b8bfb9b46-jwztv   1/1     Running   0          2m12s   172.25.78.161    k8s-worker-235ea5d4 
```

**Comment by rissson** [comment]
I'm not keen to add another template that's basically a duplicate of what is defined in the deployment one. What's the use case for this?

**Comment by eternity1984** [comment]
Hi @rissson, 

Default is `server.kind=Deployment`. Unless you explicitly set `server.kind=DaemonSet`, it will behave as before.

When using Deployment, there is no guarantee that replicas will always be placed on different nodes.
I do not want multiple replicas placed on the same node for stable operation.

**Comment by rissson** [comment]
> Sorry that this is a duplicate of Deployment. I will replace it with a pod template before making a pull request.
> 
> Default is `server.kind=Deployment`. Unless you explicitly set `server.kind=DaemonSet`, it will behave as before.

Yeah I wasn't really worried about that.

> When using Deployment, there is no guarantee that replicas will always be placed on different nodes. I do not want multiple replicas placed on the same node for stable operation.

On the contrary, you can specify affinity and anti-affinity rules so that pods will not end up on the same node: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity. In our helm chart, you can set `global.affinity.podAntiAffinity` (or override with custom rules in `server.affinity` and `worker.affinity`) to `soft` (the default) so that pods will not end up on the same node or `hard` so that they don't end up in the same zone: https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/_helpers.tpl#L66.

**Comment by eternity1984** [comment]
Thank you for your advice! :)
I'll try using `global.affinity.podAntiAffinity`

**Comment by eternity1984** [comment]
@rissson 
It worked as expected. Thanks a lot!!!

```yaml
# values.override.yaml

global:
  affinity:
    podAntiAffinity: soft

server:
  replicas: 3
  autoscaling:
    enabled: false
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
```

```
NAME                                READY   STATUS    RESTARTS   AGE     IP               NODE                  NOMINATED NODE   READINESS GATES
authentik-server-85bf8c85fb-5fmhv   1/1     Running   0          4m44s   172.25.182.101   k8s-master-2          <none>           <none>
authentik-server-85bf8c85fb-qtxnl   1/1     Running   0          2m43s   172.25.196.42    k8s-master-1          <none>           <none>
authentik-server-85bf8c85fb-sjwgw   1/1     Running   0          3m51s   172.25.168.29    k8s-master-3          <none>           <none>
```
