### ISSUE TITLE
Chart Email Settings - allow SMTP Password to be secret

### ISSUE THREAD

**Issue by andeke07** [goauthentik/helm#270]
I am using ArgoCD to configure my authentik Helm chart, and my config is stored in git. As such, if I want to configure the email settings of the Helm chart, my SMTP password is stored in the repo with the rest of my helm values.

It would be great if one could create a secret and instead of typing the password in to the values file, be able to set a secretName and key in the values file instead.

**Comment by rissson** [comment]
You can set the following in your values to achieve this:
```yaml
authentik:
  email:
  	username: file:///smtp-creds/username
	password: file:///smtp-creds/password
global:
  volumeMounts:
	- name: smtp-creds
	  mountPath: /smtp-creds
  volumes:
    - name: smtp-creds
      secret:
		secretName: authentik-smtp-credentials
```
