### ISSUE TITLE
Websockets dont work with default configuraton

### ISSUE THREAD

**Issue by hydazz** [goauthentik/helm#286]
the authentik admin ui keeps complaining that websocket connections are failing - this was not an issue before I migrated to kubernetes (was using docker+nginx reverse proxy).
I did migrate everything, including the database, so unsure if theres a hidden option in the database or whether websockets in the ingress created by the helm are dodgy

with the following values:
```yaml
  values:
    global:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media-pvc
        - name: custom-css
          configMap:
            name: authentik-custom-css
      volumeMounts:
        - name: media
          mountPath: /media
        - name: custom-css
          mountPath: /web/dist/custom.css
          subPath: custom.css
    authentik:
      secret_key: xxx
      postgresql:
        password: xxx
      email:
        host: mailxxx
        port: "587"
        username: no-reply@xxx
        password: xxx
        use_tls: true
        timeout: "30"
        from: no-reply@xxx
    server:
      ingress:
        enabled: true
        ingressClassName: external-nginx
        hosts:
          - auth.xxx
        tls:
          - secretName: wildcard.xxx
            hosts:
              - auth.xxx
      podAnnotations:
        backup.velero.io/backup-volumes: media
    postgresql:
      enabled: true
      auth:
        password: xxx
      primary:
        persistence:
          size: 256Mi
        podAnnotations:
          backup.velero.io/backup-volumes: data
    redis:
      enabled: true
      master:
        persistence:
          size: 128Mi
```
![Screenshot_20240919_223022](https://github.com/user-attachments/assets/fbda1c2f-895e-4d1b-9a1b-93acc7aedf8e)
