### ISSUE TITLE
Proxy and Redis issues

### ISSUE THREAD

**Issue by JoaoPPCastelo** [goauthentik/helm#291]
Hi all!

I was trying to deploy Authentik on a K8s cluster made of Raspberry Pis 5 (home lab) and i'm getting some issues that haven't been able to fix...

I'm using the following config
```
authentik:
  secret_key: "<redacted>"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "<redacted>"

server:
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
      - <redacted>
    tls:
      - secretName: authentik-tls
        hosts:
          - <redacted>
    https: true

postgresql:
  enabled: true
  auth:
    password: "<redacted>"
redis:
  enabled: false
```

And so far found the following errors:
- When using `redis.enabled: true`, the pod was constantly failing with the error `<jemalloc>: Unsupported system page size`. I found some issues related to this, like https://github.com/bitnami/containers/issues/26062 . There seems that a fix was provided on the latest images, and i started a container with the `bitnami/redis:latest` and at least didn't got the error, so probably authentik just needs to update to a newer tag?
- To avoid the previous error and proceed with the deployment, deployed the helm with `redis.enabled: false` and:
--  (1) both on the logs for the server and worker pods, there was a `{"event": "Redis Connection failed, retrying... (Timeout connecting to server)", "level": "info", "logger": "authentik.lib.config", "timestamp": 1729369834.256011}` error and the pods restarted. So or there's an issue on the config that is not propagating the `redis.enabled: false` to all the places it needs or redis is required?
-- (2) was getting the error `{"error":"authentik starting","event":"failed to proxy to backend","level":"warning","logger":"authentik.router","timestamp":"2024-10-19T20:31:39Z"}` on the server pod. Eventually the server pod died (failed probes?) and on the pod there was no "failed to proxy to backend" error, only the redis one, but also the pods never reached the 1/1 ready state

```
NAME                                READY   STATUS    RESTARTS        AGE
authentik-postgresql-0              1/1     Running   0               34m
authentik-server-7d7699d4d5-bsn2f   0/1     Running   3 (4m27s ago)   34m
authentik-worker-67cf9cf89-dlmzs    0/1     Running   3 (3m26s ago)   34m
```

Helm chart version 2024.8.3 from https://artifacthub.io/packages/helm/goauthentik/authentik 
Running on a k3s cluster on Raspberry Pi 5s with version v1.30.5+k3s1

Adding the logs from pods on the comments to avoid an even bigger description

But any insight on how to get an Authentik running? 
And thank you for the support
