### ISSUE TITLE
How does the authentik team wants to move forward with the Bitnami changes

### ISSUE THREAD

**Issue by Munsio** [goauthentik/helm#319]
For those who didn't know about it: https://github.com/bitnami/containers/issues/75671

With January 6th 2025 Bitnami only releases their `latest` branch for free (PostgreSQL 17) updates to older versions are going to vanish behind a paywall.

Also all free Bitnami Helm charts and containers will be subject to standard pull-rate limits and pull caps in Docker Hub. 

As the Helm chart for authentik is using PostgreSQL 16 that version will never get any security updates anymore unless switched to 17.

I am using Authentik in an homelab environment so my personal impact may not be that big and meaningful but for others it might, so I wanted to ask if you want to move forward with Bitnami charts and latest versions or if you want to switch to a different source.

**Comment by rissson** [comment]
We've seen this and are discussing it internally with the team. We'll get back here with a response once we have one. Thank you for bringing this to our attention

**Comment by Subkrys** [comment]
Hi team, any update on this topic ?

**Comment by rissson** [comment]
We've decided we will now aggressively update to the latest version of dependencies with each authentik release (excluding patches).

For the 2025.4 release:
- the Redis chart will be upgraded to the latest version. As the image is not pinned, it will also get upgraded
- the PostgreSQL chart will be upgraded to the latest version, but the image will remain pinned to `15.8.0-debian-12-r18`.

We will most likely release a 2025.5 version (otherwise it will most likely be 2025.6) with:
- the Redis chart will be ugpraded to the latest version again
- the PostgreSQL chart will be upgraded to the latest version again, and the image will no longer be pinned, which will bring it to PostgreSQL major version 17

This will require following PostgreSQL major upgrade steps, for which we provide some documentation at https://docs.goauthentik.io/docs/troubleshooting/postgres/upgrade_kubernetes.

For subsequent releases:
- the Redis chart will be upgraded to the latest version
- the PostgreSQL chart will be upgraded to the latest version, with major upgrades being called out in authentik release notes

**Comment by prom3theu5** [comment]
Just to chime in - I've been running since January with 17.2 fine

**Comment by jyoungs** [comment]
FWIW, the Argo project uses https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha ; which (having used both) I like a lot better.

**Comment by rouke-broersma** [comment]
@rissson Vmware has today announced the next phase in their scaling down of free Bitnami public catalog: https://github.com/bitnami/containers/issues/83267

TLDR; Bitnami images will only have the `latest` tag. Images will no longer be versioned depending on the upstream tool version they are using. There likely won't be any changelogs so it will be a lot of work to determine which image hash should be used to target a specific software version.

**Comment by CodeAdminDe** [comment]
I'd recommend a switch to CNPG (https://cloudnative-pg.io). I switched over months ago and it works like a charm. Official inclusion would be awesome. :) 

Anyway. I'd like to say thank you for the fact that authentik is, and stays opensource. It's the best IdP solution out there in my opinion. I hope that more people (and companies) will switch. :)

**Comment by Starttoaster** [comment]
I just pulled off a migration from bitnami/postgres to the cnpg operator that @CodeAdminDe mentioned! Basically followed the process outlined in https://docs.goauthentik.io/docs/troubleshooting/postgres/upgrade_kubernetes to dump and restore the authentik database into a cnpg cluster with the following configuration:

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
spec:
  bootstrap:
    initdb:
      database: authentik
      secret:
        name: authentik-authy-user
      owner: authy
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3
  storage:
    size: 10Gi
    storageClass: ceph-rbd
---
apiVersion: v1
stringData:
  username: authy
  password: $CNPG_AUTHENTIK_POSTGRES_PASSWORD
kind: Secret
metadata:
  name: authentik-authy-user
type: kubernetes.io/basic-auth
```

and the following helm values.yaml:

```yaml
authentik:
  secret_key: "$AUTHENTIK_SECRET_KEY"
  postgresql:
    host: "authentik-postgres-rw.authentik.svc.cluster.local"
    name: "authentik"
    user: "authy"
    password: "$CNPG_AUTHENTIK_POSTGRES_PASSWORD"
    port: 5432

postgresql:
  enabled: false

redis:
  enabled: true
  master:
    persistence:
      enabled: true
```

When I imported the database I just port forwarded the `authentik-postgres-rw.authentik.svc.cluster.local` Service.

Just in case it helps future people looking to migrate away from bitnami resources. Now I just need to migrate off of the redis chart...
