### ISSUE TITLE
Clean installing fails on postgresql error

### ISSUE THREAD

**Issue by JustScreaMy** [goauthentik/helm#323]
Hello,
I have recently tried to install the version `2024.12.3` on my cluster using the tutorial with a small changes, but I have always ended on postgresql errors:
```
2025-02-01 11:27:43.355 GMT [107[] DETAIL:  Role "authentik" does not exist.
    Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

My Values.yaml looks like this:
```yaml
postgresql:
  enabled: true
  auth:
    password: "myVerySecretPassword"

authentik:
  secret_key: "myVerySecretSecret"

  postgresql:
    password: "myVerySecretPassword"

redis:
  enabled: true

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - idp.example.com
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: cloudflare-issuer
    tls:
      - hosts: 
        - idp.example.com
        secretName: authentik-tls
```
