### ISSUE TITLE
Using Authentik as a subchart - need postgresql upgrade

### ISSUE THREAD

**Issue by blinky-z** [goauthentik/helm#332]
I use Authentik as a subchart, installing it to the separate namespace alongside the main chart. But that seems to be impossible.

The Bitnami's PostgreSQL chart used by this chart is obsolete and doesn't respect the `namespaceOverride` value. Therefore it's getting installed in the release namespace, not in the one specified by `namespaceOverride`.

The newest PostgreSQL chart (16.4) does respect this value. Please upgrade the chart :)

Here's my configuration:
```yaml
authentik:
    namespaceOverride: authentik # this chart itself (worker, server) is OK
    authentik:
        enabled: true
        secret_key: "<secret>"
        postgresql:
            password: "<secret>"
    server:
        metrics:
            enabled: false
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - authentik.domain.tld
    serviceAccount:
        create: false
    # postgresql bitnami subchart
    postgresql:
        enabled: true
        namespaceOverride: authentik # NOT USED
        auth:
            password: "<secret>"
    # redis bitnami subchart
    redis:
        enabled: true
        namespaceOverride: authentik # Redis chart is OK
```
