### ISSUE TITLE
Unable to deploy using sample values file

### ISSUE THREAD

**Issue by pyhoff** [goauthentik/helm#358]
Followed your sample guide just to see if it works,can't even get sample Values.yaml file to work.
```
authentik:
    secret_key: "over50charstring"
    error_reporting:
        enabled: true
    postgresql:
        password: "someComplexPassword"
server:
    ingress:
        ingressClassName: traefik
        enabled: true
        hosts:
            - "auth.DOMAIN.com"
postgresql:
    enabled: true
    auth:
        password: "someComplexPassword"
redis:
    enabled: true
```
---  
ERROR:
```    
helm repo add authentik https://charts.goauthentik.io
helm repo update
helm upgrade --install authentik authentik/authentik -f values.yaml
"authentik" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "authentik" chart repository
Update Complete. ⎈Happy Helming!⎈
Release "authentik" does not exist. Installing it now.
Error: template: authentik/templates/worker/deployment.yaml:35:28: executing "authentik/templates/worker/deployment.yaml" at <include (print $.Template.BasePath "/secret.yaml") .>: error calling include: template: authentik/templates/secret.yaml:14:6: executing "authentik/templates/secret.yaml" at <include "authentik.env" (dict "root" . "values" .Values.authentik)>: error calling include: template: authentik/templates/_helpers.tpl:35:20: executing "authentik.env" at <include "authentik.env" (dict "root" $.root "values" (dict (printf "%s__%s" (upper $k) (upper $sk)) $sv))>: error calling include: template: authentik/templates/_helpers.tpl:42:29: executing "authentik.env" at <$v>: wrong type for value; expected string; got json.Number
```
