### ISSUE TITLE
Redis: Error 111 connecting to None:6379. Connection refused.

### ISSUE THREAD

**Issue by Nold360** [goauthentik/helm#39]
Hi,

i wanted to give authentik a shot & ran into this issue. 

authentik-server:
```
{"event": "Redis Connection failed, retrying... (Error 111 connecting to None:6379. Connection refused.)", "level": "info", "logger": "__main__", "timestamp": 1637770878.299152}
```

So i guess the redis hostname is not set correctly. But I checked the ENV and is seems correct: `AUTHENTIK_REDIS__HOST: authentik-redis-master`

Here are the rest of my values:
``` yaml
ingress:
  enabled: true
  ingressClassName: ""
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
  hosts:
    - host: auth.dc
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts: ['auth.dc']
      secretName: "auth-tls"

authentik:
  # -- Log level for server and worker
  log_level: info
  # -- Secret key used for cookie singing and unique user IDs,
  # don't change this after the first install
  secret_key: ""
  # -- Path for the geoip database. If the file doesn't exist, GeoIP features are disabled.
  geoip: /geoip/GeoLite2-City.mmdb
  # -- Mode for the avatars. Defaults to gravatar. Possible options 'gravatar' and 'none'
  avatars: none

  postgresql:
    # -- set the postgresql hostname to talk to
    # if unset and .Values.postgresql.enabled == true, will generate the default
    # @default -- `{{ .Release.Name }}-postgresql`
    host: '{{ .Release.Name }}-postgresql'
    # -- postgresql Database name
    # @default -- `authentik`
    name: "authentik"
    # -- postgresql Username
    # @default -- `authentik`
    user: "authentik"
    port: 5432
  redis:
    # -- set the redis hostname to talk to
    # @default -- `{{ .Release.Name }}-redis-master`
    host: '{{ .Release.Name }}-redis-master'


envValueFrom:
  AUTHENTIK_SECRET_KEY:
    secretKeyRef:
      key: secret_key
      name: authentik
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      key: postgresql-password
      name: postgres
  AUTHENTIK_REDIS__PASSWORD:
    secretKeyRef:
      key: password
      name: redis


postgresql:
  # -- enable the bundled bitnami postgresql chart
  enabled: true
  postgresqlUsername: "authentik"
  # postgresqlPassword: ""
  postgresqlDatabase: "authentik"
  persistence:
    enabled: true
  #  storageClass:
    accessModes:
      - ReadWriteOnce
  existingSecret: postgres

redis:
  # -- enable the bundled bitnami redis chart
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis
    existingSecretPasswordKey: password
```

Chart Version: 4.0.3
