### ISSUE TITLE
Add ability to add additional sidecars and init containers in the Helm chart

### ISSUE THREAD

**Issue by sarahhenkens** [goauthentik/helm#43]
To support Cloud SQL connectivity in GKE, the Authentik pod needs to have an additional sidecar that does the proxying. Currently, the helm chart does not support adding additional sidecars.

A great example from the[ Vault helm chart](https://github.com/hashicorp/vault-helm):

https://github.com/hashicorp/vault-helm/blob/main/values.yaml#L326-L346
```yaml
  # extraInitContainers is a list of init containers. Specified as a YAML list.
  # This is useful if you need to run a script to provision TLS certificates or
  # write out configuration files in a dynamic way.
  extraInitContainers: null
    # # This example installs a plugin pulled from github into the /usr/local/libexec/vault/oauthapp folder,
    # # which is defined in the volumes value.
    # - name: oauthapp
    #   image: "alpine"
    #   command: [sh, -c]
    #   args:
    #     - cd /tmp &&
    #       wget https://github.com/puppetlabs/vault-plugin-secrets-oauthapp/releases/download/v1.2.0/vault-plugin-secrets-oauthapp-v1.2.0-linux-amd64.tar.xz -O oauthapp.xz &&
    #       tar -xf oauthapp.xz &&
    #       mv vault-plugin-secrets-oauthapp-v1.2.0-linux-amd64 /usr/local/libexec/vault/oauthapp &&
    #       chmod +x /usr/local/libexec/vault/oauthapp
    #   volumeMounts:
    #     - name: plugins
    #       mountPath: /usr/local/libexec/vault

  # extraContainers is a list of sidecar containers. Specified as a YAML list.
  extraContainers: null
```

And inside the deployment:
```yaml
{{- if .Values.server.extraInitContainers }}
initContainers:
  {{ toYaml .Values.server.extraInitContainers | nindent 8}}
{{- end }}
```

```yaml
{{- if .Values.server.extraContainers }}
  {{ toYaml .Values.server.extraContainers | nindent 8}}
{{- end }}
```
