### ISSUE TITLE
Chart version 5.2.2 populates empty envVars causing envFrom.. not to work

### ISSUE THREAD

**Issue by anthr76** [goauthentik/helm#58]
Chart version: 5.2.2

This is portion of my deployment spec

...
```yaml
    spec:
      containers:
      - args:
        - server
        env:
        - name: AUTHENTIK_AVATARS
          value: gravatar
        - name: AUTHENTIK_EMAIL__FROM
        - name: AUTHENTIK_EMAIL__HOST
        - name: AUTHENTIK_EMAIL__PASSWORD
        - name: AUTHENTIK_EMAIL__PORT
          value: "587"
        - name: AUTHENTIK_EMAIL__TIMEOUT
          value: "30"
        - name: AUTHENTIK_EMAIL__USE_SSL
          value: "false"
        - name: AUTHENTIK_EMAIL__USE_TLS
          value: "false"
        - name: AUTHENTIK_EMAIL__USERNAME
        - name: AUTHENTIK_ERROR_REPORTING__ENABLED
          value: "false"
        - name: AUTHENTIK_ERROR_REPORTING__ENVIRONMENT
          value: k8s
        - name: AUTHENTIK_ERROR_REPORTING__SEND_PII
          value: "false"
        - name: AUTHENTIK_GEOIP
          value: /geoip/GeoLite2-City.mmdb
        - name: AUTHENTIK_LOG_LEVEL
          value: debug
        - name: AUTHENTIK_OUTPOSTS__CONTAINER_IMAGE_BASE
          value: ghcr.io/goauthentik/%(type)s:%(version)s
        - name: AUTHENTIK_POSTGRESQL__HOST
          value: authentik-postgres
        - name: AUTHENTIK_POSTGRESQL__NAME
          value: postgres
        - name: AUTHENTIK_POSTGRESQL__PORT
          value: "5432"
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__ACCESS_KEY
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__BUCKET
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__HOST
        - name: AUTHENTIK_SECRET_KEY
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__INSECURE_SKIP_VERIFY
          value: "false"
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__LOCATION
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__REGION
        - name: AUTHENTIK_POSTGRESQL__S3_BACKUP__SECRET_KEY
        - name: AUTHENTIK_POSTGRESQL__USER
          value: postgres
        - name: AUTHENTIK_REDIS__HOST
          value: authentik-redis-master
        envFrom:
        - secretRef:
            name: authentik
```

My envFrom secret has important values like `AUTHENTIK_SECRET_KEY` and such but it's getting overwritten from blank env vars
