### ISSUE TITLE
PostgreSQL Password

### ISSUE THREAD

**Issue by MrMarble** [goauthentik/helm#61]
I'm having some problems deploying this helm chart. Running version 5.2.3

Logs:
authentik-worker
```jsonc
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.43.143.115), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1647281978.839573}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1647281978.8397024}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.43.143.115), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1647281979.8466108}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1647281979.846741}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.43.143.115), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1647281980.8527002}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1647281980.8528295}
// repeated endessly
```
authentik-server
```jsonc
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.43.143.115), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1647281849.623484}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1647281849.623618}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.43.143.115), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1647281850.6303198}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1647281850.630462}
{"event": "PostgreSQL connection failed, retrying... (connection to server at \"authentik-postgresql\" (10.43.143.115), port 5432 failed: FATAL:  password authentication failed for user \"authentik\"\n)", "level": "info", "logger": "__main__", "timestamp": 1647281851.6366813}
{"event": "PostgreSQL connection successful", "level": "info", "logger": "__main__", "timestamp": 1647281851.6368034}
// repeated endessly
```

authentik-postgresql
```bash
2022-03-14 18:15:35.212 GMT [112] FATAL:  password authentication failed for user "authentik"
2022-03-14 18:15:35.212 GMT [112] DETAIL:  Password does not match for user "authentik".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

Describing the secrets, both `authentik-postgresql` and `authentik-secrets` are the same.

Here is my Helm release:
```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: 5.2.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2022.3.1
    authentik:
      error_reporting:
        enabled: false
      log_level: "debug"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      hosts:
        - host: "authentik.${SECRET_DOMAIN}"
          paths:
            - path: "/"
              pathType: Prefix
      tls:
        - hosts:
            - "authentik.${SECRET_DOMAIN}"
          secretName: "authentik-tls"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "shield-key"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    postgresql:
      enabled: true
    redis:
      enabled: true
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true

  valuesFrom:
    - kind: Secret
      name: authentik-secrets
```

and here my secrets:

```yaml
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: auth
type: Opaque
stringData:
    values.yaml: |
        postgresql:
          postgresqlPassword: "password" # not real
        authentik:
          postgresql:
            password: "password"
          secret_key: "karaoke" # not real

```
